version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development  # Optional, helps debug

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
