version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development  # This is fine, even in "production"
      - DATABASE_URL=postgresql://admin:password@postgres:5432/draftempire
      - POSTGRES_HOST=postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"  # ✅ Nginx serves the built files
    depends_on:
      - backend
    networks:
      - app-network    
    # command: [ "nginx", "-g", "daemon off;" ]  # ✅ Runs Nginx properly

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: draftempire
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin 

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
