name: Auto Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf ~/myapp
            git clone git@github.com:Chad-111/myapp.git ~/myapp
            cd ~/myapp
            git reset --hard origin/main
            git clean -fdx  # 🚨 Wipes all untracked files
            docker-compose down
            docker-compose build --no-cache  # 🚨 No Docker cache
            docker-compose up -d
            docker system prune -f -a --volumes
