name: Auto Deploy Frontend and Backend

on:
  push:
    branches:
      - main  # ✅ Runs every time you push to `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/myapp
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker system prune -f  # Cleans up old images
