name: Auto Deploy Frontend and Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/myapp  # <-- make sure everything is gone
            git clone --depth=1 git@github.com:Chad-111/myapp.git ~/myapp
            cd ~/myapp
            docker-compose down
            docker-compose up -d --build
            docker system prune -f

